\
#!/usr/bin/env bash
set -euo pipefail

# Generated by DWH Export Wizard
# Consolidates chunk files *_000_YYYYMMDDHHMMSS.csv ... *_009_YYYYMMDDHHMMSS.csv
# into one file *_consolidated_YYYYMMDDHHMMSS.csv (with src prefix in each row),
# then archives chunk files into ./00X_files

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$WORKSPACE_DIR/config.env"
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "❌ Missing config.env"
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

BASE_DIR="$OUTPUT_DIR"
ARCHIVE_DIR="$BASE_DIR/00X_files"

DATE="${1:-$(date +%Y%m%d)}"
TS="$(date +%Y%m%d%H%M%S)"

mkdir -p "$ARCHIVE_DIR"
cd "$BASE_DIR" || { echo "❌ Cannot cd to $BASE_DIR"; exit 1; }

# Optional filter file (created by wizard) that lists allowed base prefixes (one per line)
FILTER_FILE="$WORKSPACE_DIR/consolidate_allowlist.txt"
ALLOWLIST=()
if [[ -f "$FILTER_FILE" ]]; then
  mapfile -t ALLOWLIST < "$FILTER_FILE"
fi

is_allowed_prefix() {
  local p="$1"   # e.g. BILL#bill_transaction
  if [[ ${#ALLOWLIST[@]} -eq 0 ]]; then
    return 0
  fi
  local base="${p#*#}" # remove domain#
  for a in "${ALLOWLIST[@]}"; do
    [[ -z "$a" ]] && continue
    # Allow either exact base match or domain#base match
    if [[ "$a" == "$base" || "$a" == "$p" ]]; then
      return 0
    fi
  done
  return 1
}

echo "🌀 Consolidation for date: $DATE"
shopt -s nullglob
FILES=(*\#*_[0-9][0-9][0-9]_"${DATE}"??????.csv)
shopt -u nullglob

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "❌ No chunk files found for date $DATE in $BASE_DIR"
  exit 1
fi

# Detect unique prefixes: DOMAIN#table (strip _000_DATEHHMMSS.csv)
mapfile -t PREFIXES < <(for f in "${FILES[@]}"; do
  echo "$f" | sed -E "s/_([0-9]{3})_${DATE}[0-9]{6}\.csv$//"
done | sort -u)

for prefix in "${PREFIXES[@]}"; do
  if ! is_allowed_prefix "$prefix"; then
    echo "⏭ Skipping (not in allowlist): $prefix"
    continue
  fi

  echo "📌 Processing prefix: $prefix"
  OUTFILE="${prefix}_consolidated_${TS}.csv"
  : > "$OUTFILE"

  # chunk matches
  shopt -s nullglob
  MATCHES=(${prefix}_[0-9][0-9][0-9]_"${DATE}"??????.csv)
  shopt -u nullglob

  if [[ ${#MATCHES[@]} -eq 0 ]]; then
    echo "⚠️ No matches for $prefix"
    continue
  fi

  for f in "${MATCHES[@]}"; do
    SOURCE_NAME=$(echo "$f" | sed -E "s/^.*#//; s/_${DATE}[0-9]{6}\.csv$//")
    echo "   ➕ Adding $f → $OUTFILE as $SOURCE_NAME"
    awk -v src="$SOURCE_NAME" '{print src "|" $0}' "$f" >> "$OUTFILE"
  done

  echo "📦 Archiving chunk files to $ARCHIVE_DIR"
  mv "${MATCHES[@]}" "$ARCHIVE_DIR/"

  echo "✅ Created: $OUTFILE"
done

echo "🎉 Consolidation completed!"
