\
#!/usr/bin/env bash
set -euo pipefail

# Generated by DWH Export Wizard
# Uses config.env + queries.sh + (optional) domains.sh

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$WORKSPACE_DIR/config.env"
QUERY_FILE="$WORKSPACE_DIR/queries.sh"
DOMAIN_FILE="$WORKSPACE_DIR/domains.sh"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "❌ Missing config.env in $WORKSPACE_DIR"
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

if [[ ! -f "$QUERY_FILE" ]]; then
  echo "❌ Missing queries.sh in $WORKSPACE_DIR"
  exit 1
fi
# shellcheck disable=SC1090
source "$QUERY_FILE"

if [[ -f "$DOMAIN_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$DOMAIN_FILE"
fi

mkdir -p "$OUTPUT_DIR"

timestamp="$(date +%Y%m%d%H%M%S)"

echo "📦 Output folder: $OUTPUT_DIR"
echo "🕒 Timestamp: $timestamp"

# --- secure_file_priv detection (optional) ---
SECURE_DIR="$("$MYSQL_BIN" -u"$MYSQL_USER" -p"$MYSQL_PASS" -S "$MYSQL_SOCKET" -Nse \
  "SHOW VARIABLES LIKE 'secure_file_priv';" 2>/dev/null | awk '{print $2}' || true)"
MYSQL_OUTDIR="${SECURE_DIR:-}"

if [[ -n "$MYSQL_OUTDIR" && "$MYSQL_OUTDIR" != "NULL" ]]; then
  echo "🔒 MySQL secure_file_priv: $MYSQL_OUTDIR"
else
  echo "⚠️ secure_file_priv not set or not readable; will attempt to use OUTPUT_DIR via temporary file method."
fi

# Function: find domain for a given query variable (if domains.sh is present)
get_domain() {
  local qname="$1"
  if declare -p DOMAIN_QUERIES >/dev/null 2>&1; then
    for domain in "${!DOMAIN_QUERIES[@]}"; do
      if echo "${DOMAIN_QUERIES[$domain]}" | grep -qw "$qname"; then
        echo "$domain"
        return
      fi
    done
  fi
  echo "UNKNOWN"
}

# Export query to CSV file with | delimiter
export_one() {
  local var="$1"
  local query="${!var}"
  local table
  table="$(echo "$var" | sed 's/^Q_//')"
  local domain
  domain="$(get_domain "$var")"

  # Clean query (remove trailing semicolon)
  local query_no_semicolon
  query_no_semicolon="$(echo "$query" | sed 's/;[[:space:]]*$//')"

  local final_file="$OUTPUT_DIR/${domain}#${table}_${timestamp}.csv"

  # Prefer INTO OUTFILE when allowed (fast), otherwise fall back to stdout redirection.
  if [[ -n "${MYSQL_OUTDIR:-}" && "${MYSQL_OUTDIR:-}" != "NULL" ]]; then
    local tmp_outfile="$MYSQL_OUTDIR/${domain}#${table}_${timestamp}_raw.csv"
    local data_query="${query_no_semicolon}
INTO OUTFILE '${tmp_outfile}'
FIELDS TERMINATED BY '|'
OPTIONALLY ENCLOSED BY '\"'
LINES TERMINATED BY '\n';"
    echo "📤 Exporting: $domain → $table (INTO OUTFILE)"
    "$MYSQL_BIN" -u"$MYSQL_USER" -p"$MYSQL_PASS" -S "$MYSQL_SOCKET" "$MYSQL_DB" -e "$data_query"
    sed 's/"//g; s/\\N//g' "$tmp_outfile" > "$final_file"
    rm -f "$tmp_outfile"
  else
    echo "📤 Exporting: $domain → $table (STDOUT fallback)"
    "$MYSQL_BIN" -u"$MYSQL_USER" -p"$MYSQL_PASS" -S "$MYSQL_SOCKET" "$MYSQL_DB" -N -e "$query_no_semicolon" \
      | awk 'BEGIN{OFS="|"}{print $0}' > "$final_file"
  fi

  echo "✅ Generated: $final_file"
}

# Loop through all Q_* variables
for var in $(compgen -A variable | grep '^Q_'); do
  export_one "$var"
done

echo "🎉 Export completed."
