\
#!/usr/bin/env bash
set -euo pipefail

# Generated by DWH Export Wizard
# Upload all CSV files from OUTPUT_DIR to remote destination folder via SFTP.

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$WORKSPACE_DIR/config.env"
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "❌ Missing config.env"
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

LOG_FILE="$WORKSPACE_DIR/upload_$(date +%Y%m%d).log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "[$(date)] 🚀 Upload started"
echo "[$(date)] 📁 Local: $OUTPUT_DIR"
echo "[$(date)] 🌐 Remote: $SFTP_USER@$SFTP_HOST:$SFTP_REMOTE_DIR"
echo "[$(date)] 🔐 Auth: $SFTP_MODE"

shopt -s nullglob
FILES=("$OUTPUT_DIR"/*.csv)
shopt -u nullglob

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "[$(date)] ⚠️ No CSV files to upload."
  exit 0
fi

# Build batch file
BATCH="$(mktemp)"
for f in "${FILES[@]}"; do
  b="$(basename "$f")"
  echo "put \"$f\" \"$SFTP_REMOTE_DIR/$b\"" >> "$BATCH"
done

# Ensure remote dir exists (best effort)
mkdir_batch="$(mktemp)"
cat > "$mkdir_batch" <<EOF
mkdir "$SFTP_REMOTE_DIR"
EOF

if [[ "$SFTP_MODE" == "password" ]]; then
  if ! command -v sshpass >/dev/null 2>&1; then
    echo "❌ sshpass is required for password-based SFTP but is not installed."
    echo "   Install it (example Debian/Ubuntu): sudo apt-get install sshpass"
    rm -f "$BATCH" "$mkdir_batch"
    exit 1
  fi

  sshpass -p "$SFTP_PASS" sftp -oStrictHostKeyChecking=no -b "$mkdir_batch" "$SFTP_USER@$SFTP_HOST" </dev/null || true
  sshpass -p "$SFTP_PASS" sftp -oStrictHostKeyChecking=no -b "$BATCH" "$SFTP_USER@$SFTP_HOST" </dev/null
else
  # key mode
  sftp -oIdentityFile="$SFTP_KEY_PATH" -oStrictHostKeyChecking=no -b "$mkdir_batch" "$SFTP_USER@$SFTP_HOST" </dev/null || true
  sftp -oIdentityFile="$SFTP_KEY_PATH" -oStrictHostKeyChecking=no -b "$BATCH" "$SFTP_USER@$SFTP_HOST" </dev/null
fi

rm -f "$BATCH" "$mkdir_batch"
echo "[$(date)] 🎉 Upload completed"
